language: python
python:
 - "3.4"
 - "3.5"
# command to install dependencies
env:
  - DJANGO_VERSION=1.8.5
services:
  - elasticsearch
install: 
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
  - pip install -r elastic/requirements.txt || true
before_script:
  - django-admin startproject elastic_test
  - ls -l
  - ls -l elastic_test/
  - 'command echo ''{"a": 1, "b": 2}'''
  - sed -i "s|INSTALLED_APPS = (|INSTALLED_APPS = ('elastic',|" elastic_test/elastic_test/settings.py
  - 'command echo ''ELASTIC = {"default": { "ELASTIC_URL": "http://127.0.0.1:9200/", "IDX": {"MARKER": {"name": "dbsnp142", "idx_type": {"MARKER": "marker"}}, "DEFAULT": "dbsnp142",},"TEST": "test_django_elastic_tc", "TEST_REPO_DIR": "/tmp/test_snapshot/", "REPOSITORY": "my_backup",}}'' >> elastic_test/elastic_test/settings.py'
  - tail -100 elastic_test/elastic_test/settings.py
  - echo "urlpatterns += [url(r'^search/', include('elastic.urls', namespace='elastic')),]" >> elastic_test/elastic_test/urls.py 
  - sleep 10
# command to run tests
script: 
  - time 
  - elastic_test/manage.py test elastic.tests -v3 --noinput
